matrix:
        include:
                - language: clojure
                  before_install: cd backend
                  script:
                          - lein test
                          - lein yagni
                          - lein eastwood
                          - lein cloverage
                - language: node_js
                  before_install: cd frontend
                  install: yarn install
                  sccript: yarn test

notifications:
    email: false
