matrix:
        include:
                - language: clojure
                  script:
                          - lein test
                          - lein yagni
                          - lein eastwood
                          - lein cloverage
                - language: node_js

notifications:
    email: false
