matrix:
        include:
                - language: clojure
                  before_script: cd backend
                  script:
                          - lein test
                          - lein yagni
                          - lein eastwood
                          - lein cloverage
                - language: node_js
                  before_script: cd frontend

notifications:
    email: false
